"""empty message

Revision ID: ac6888546ec8
Revises: 6296582236e5
Create Date: 2021-07-05 15:15:29.037544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6888546ec8'
down_revision = '6296582236e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('show', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
